qemu 8.2.2
autobump: add qemu

Signed-off-by: Rui Chen <rui@chenrui.dev>

qemu: need `python-setputools` build dep

```
  FAILED: ui/dbus-display1.h ui/dbus-display1.c
  /home/linuxbrew/.linuxbrew/Cellar/glib/2.78.4/bin/gdbus-codegen ui/dbus-display1.xml --glib-min-required 2.64 --output-directory /tmp/qemu-20240305-18617-7txoh/qemu-8.2.2/build/ui --interface-prefix org.qemu. --c-namespace QemuDBus --generate-c-code dbus-display1
  Traceback (most recent call last):
    File "/home/linuxbrew/.linuxbrew/Cellar/glib/2.78.4/bin/gdbus-codegen", line 53, in <module>
      from codegen import codegen_main
    File "/home/linuxbrew/.linuxbrew/Cellar/glib/2.78.4/share/glib-2.0/codegen/codegen_main.py", line 29, in <module>
      from . import dbustypes
    File "/home/linuxbrew/.linuxbrew/Cellar/glib/2.78.4/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
      from . import utils
    File "/home/linuxbrew/.linuxbrew/Cellar/glib/2.78.4/share/glib-2.0/codegen/utils.py", line 22, in <module>
      import distutils.version
  ModuleNotFoundError: No module named 'distutils'
```

Signed-off-by: Rui Chen <rui@chenrui.dev>